[profile.default]
src = "contracts"
out = "artifacts"
test = "contracts/test"
libs = ["node_modules", "lib"]

sort_imports = true
line_length = 100

remappings = [
    "@1inch/=node_modules/@1inch/",
    "@ethereum-waffle/=node_modules/@ethereum-waffle/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
